---
title: "Ideias"
page-layout: full
---

# Projectos/Teses

- Sistema de vigilância autónomo com base em UAS e visão computacional 
  - Docking station (PILAV, entregue 23/24 S1) Proposta escrita e atribuida 
  - Detection [Prosta escrita, sem alunos ]
  - Navigation [Prosta escrita, sem alunos ]
- Shiping container survey with autonomous UAVs 
  - SLAM & container detection
  - Path planning, with energy minimization and specific sensor constraints
- AntiUAS, AntiAntiUAS 
  - Comparative analysis of AntiUAS systems (EW – jamming, spoofing, cyber; physical – kinectic, laser, nets, ground vs air based; what to do against deadreckoning and vision perception?) 
  - Development of printable adversarial examples against common open-source off-the-shelf detection models using aerial imagery for protecting VIPs 
  - Robust UAS protocols against cyber attacks (takeover, etc.) 
  - Development of online path planning module for multirotor UAV, to create robust paths against antiUAS systems (kinectic, laser) 
  - Use of cognitive radios with SDR to increase robustness of Communications and defeat antiUAS 
- FOD (follow up [João Almeida](https://www.researchgate.net/profile/Goncalo-Cruz-2/publication/368568586_Application_of_Deep_Learning_to_the_Detection_of_Foreign_Object_Debris_at_Aerodromes'_Movement_Area/links/64bbf6fb8de7ed28bab83ce0/Application-of-Deep-Learning-to-the-Detection-of-Foreign-Object-Debris-at-Aerodromes-Movement-Area.pdf){target="_blank"}) 
  - [repeat work with new array of sensors](#repeat-work-with-new-array-of-sensors)
  - [Depth estimation FOD](#depth-estimation-fod)
- Marker based localization (follow-up J. Rocha)
  - repetir c/ alvo móvel, vento, gimbal low-cost (TODO tese de controlo, colaboração externa)
    - podemos testar a stack actual com alvo móvel e verificar o comportamento do sistema
  - Criação de área de testes, c/ localização à base de markers e hardware low-cost (percepção e computação) TODO 
- RL-based autolanding controller for low-cost VTOL UAV
- RL-based controller for tail sitter (tangente R. Rocha)
- [HMI registo ações manutenção](#hmi-registo-ações-manutenção)
- Autonomous Unmanned Ground Vehicle (AUGV) (POC: CAP Silva)
  - Use case: landing for drone (Holybro, good for testing auto landing system in mobile targets)
  - Mechanical eng. (construction, mobility, ...)
  - Perception (cameras, depth, LIDAR, ...)
  - Electronics (energy management, sensors, actuactors, ...)
  - Software development (architecture, communication, middleware, integration, ...)


# Miniprojectos

- Add gimbal camera do Gazebo models for UAV simulation (POC: CAP Silva)
  - Camera
  - Gimbal
- Auto shutdown and boot up of PCs (POC: CAP Silva)
  - Raspberry UPS (hardware, electronics)
  - Dashboard for configuration and control (Python, webdevelopment)
- Low cost gimbal | RaspiCam | 3d printed | servo/BLDC
  - 3d model and 3d printing of support (POC: TEN Vasco Coelho / CAP Silva)
  - Controller (software, ROS, Python, POC: CAP Silva)
  - Sources:
    - https://hackaday.com/2019/08/19/diy-gimbal-for-the-raspberry-pi-camera/
    - https://thepihut.com/products/pan-tilt-platform-for-official-raspberry-pi-camera-module
- Instrumentação da bancada de testes de propulsão de motores (POC: TEN Coelho)


# repeat work with new array of sensors

- Repetir a recolha de dados do J. Almeida com mais sensores, e.g. estereo, lidar, laser rangefinder, etc.
- Identificar oportunidades de labeling automático com base em distância a objectos
- Desenvolvimento de modelos multi-modais
- Comparar cada modalidade

# Depth estimation FOD

- Com base no dataset construido em [Almeida follow-up](#repeat-work-with-new-array-of-sensors), desenvolver modelos de monocolar depth estimation.


# HMI registo ações manutenção

- Do trabalho da tese da M. Fontainha, constatou-se que existe uma grande percentagem de erros no dataset das acções de manutenção.
- A falta de usabilidade e morosidade do processo são apontados como possíveis fontes do problema.
- Resumidamente, o processo atual envolve acesso a um computador com rede interna, login no sistema, identificar as peças que sofreram intervenção, indicar o número de horas dispendido e escolher o identificador (de uma lista de algumas centenas) que mais se adequa à intervenção.
- Foi verificado que de toda esta lista, a distribuição dos identificadores selecionados está altamente enviesada para um pequeno subset dos disponíveis. Foi colocada a hipótese de os mecânicos selecionarem apenas uma das opções deste subset para acelerar o processo, evitando demorar tempo no processo de procura do identificador correcto.

Com este trabalho exploratório pretende-se:

1. comunicar com o "cliente" final (os mecânicos) para descrever o processo actual e identificar os pontos de atrito e o que pode ser melhorado
2. identificar formas de acelerar a introdução dos dados da acção de manutenção, nomeadamente
  - alternativas para introdução em computador
  - como identificar mais rapidamente as peças que sofreram intervenção
  - como identificar mais rapidamente o identificador correcto (e.g. árvore de decisão)

Trabalho tangente:

- seria possível um pré-registo automático com base em visão computacional?


